#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import { ImageGeneratorStack } from '../lib/image-generator-stack';

const app = new cdk.App();
new ImageGeneratorStack(app, 'ImageGeneratorStack', {
  env: {
    account: process.env.CDK_DEFAULT_ACCOUNT,
    region: process.env.CDK_DEFAULT_REGION,
  },
});

